# Generated by Django 4.2.7 on 2023-11-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=255)),
                ("creation_datetime", models.DateTimeField(auto_now=True)),
                ("deadline", models.DateTimeField(null=True)),
                ("is_done", models.BooleanField()),
                ("tags", models.ManyToManyField(related_name="tags", to="app.tag")),
            ],
        ),
    ]
